# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\musta\Desktop\SportParkiProjesi\salonPicturePage.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import SkateBoard
import Fitness
import swimming
import Walking
class Ui_Dialog(object):
    def goSwim(self):
        self.window = QtWidgets.QWidget()
        self.ui = swimming.Ui_Dialog()
        self.ui.setupUi(self.window)
        self.window.show()
    def goWalking(self):
        self.window = QtWidgets.QWidget()
        self.ui = Walking.Ui_Dialog()
        self.ui.setupUi(self.window)
        self.window.show()
    def goFitness(self):
        self.window = QtWidgets.QWidget()
        self.ui = Fitness.Ui_Dialog()
        self.ui.setupUi(self.window)
        self.window.show()
    def goSkateBoard(self):
        self.window = QtWidgets.QWidget()
        self.ui = SkateBoard.Ui_Dialog()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(653, 623)
        Dialog.setStyleSheet("background-color: #83230E;\n"
"color: white;")
        self.labelTitle = QtWidgets.QLabel(Dialog)
        self.labelTitle.setGeometry(QtCore.QRect(39, 20, 571, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitle.setFont(font)
        self.labelTitle.setObjectName("labelTitle")
        self.closebutton = QtWidgets.QPushButton(Dialog)
        self.closebutton.setGeometry(QtCore.QRect(40, 570, 571, 31))
        self.closebutton.setStyleSheet("background-color: white; color: black")
        self.closebutton.setObjectName("closebutton")
        self.closebutton.clicked.connect(Dialog.close)
        self.photo2 = QtWidgets.QLabel(Dialog)
        self.photo2.setGeometry(QtCore.QRect(360, 80, 251, 191))
        self.photo2.setStyleSheet("border: 2px solid black;border-image: url(resim3.jpg);")
        self.photo2.setText("")
        self.photo2.setObjectName("photo2")
        self.photo1 = QtWidgets.QLabel(Dialog)
        self.photo1.setGeometry(QtCore.QRect(40, 80, 261, 191))
        self.photo1.setStyleSheet("border: 2px solid black; border-image: url(resim4.jpg);")
        self.photo1.setText("")
        self.photo1.setObjectName("photo1")
        self.detailButton1 = QtWidgets.QPushButton(Dialog)
        self.detailButton1.setGeometry(QtCore.QRect(230, 280, 71, 21))
        self.detailButton1.setStyleSheet("background-color: white; color: black")
        self.detailButton1.setObjectName("detailButton1")
        self.detailButton1.clicked.connect(self.goSkateBoard)
        self.nameLabel1 = QtWidgets.QLabel(Dialog)
        self.nameLabel1.setGeometry(QtCore.QRect(50, 280, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel1.setFont(font)
        self.nameLabel1.setObjectName("nameLabel1")
        self.nameLabel1.setText("Swimming")
        self.detailButton1_2 = QtWidgets.QPushButton(Dialog)
        self.detailButton1_2.setGeometry(QtCore.QRect(540, 280, 71, 21))
        self.detailButton1_2.setStyleSheet("background-color: white; color: black")
        self.detailButton1_2.setObjectName("detailButton1_2")
        self.detailButton1_2.clicked.connect(self.goWalking)
        self.nameLabel1_2 = QtWidgets.QLabel(Dialog)
        self.nameLabel1_2.setGeometry(QtCore.QRect(360, 280, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel1_2.setFont(font)
        self.nameLabel1_2.setObjectName("nameLabel1_2")
        self.nameLabel1_2.setText("Walking")
        self.detailButton1_4 = QtWidgets.QPushButton(Dialog)
        self.detailButton1_4.setGeometry(QtCore.QRect(540, 520, 71, 21))
        self.detailButton1_4.setStyleSheet("background-color: white; color: black")
        self.detailButton1_4.setObjectName("detailButton1_4")
        self.detailButton1_4.clicked.connect(self.goFitness)
        self.detailButton1_3 = QtWidgets.QPushButton(Dialog)
        self.detailButton1_3.setGeometry(QtCore.QRect(230, 520, 71, 21))
        self.detailButton1_3.setStyleSheet("background-color: white; color: black")
        self.detailButton1_3.setObjectName("detailButton1_3")
        self.detailButton1_3.clicked.connect(self.goSwim)
        self.nameLabel1_3 = QtWidgets.QLabel(Dialog)
        self.nameLabel1_3.setGeometry(QtCore.QRect(50, 520, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel1_3.setFont(font)
        self.nameLabel1_3.setObjectName("nameLabel1_3")
        self.nameLabel1_3.setText("Label3")
        self.photo4 = QtWidgets.QLabel(Dialog)
        self.photo4.setGeometry(QtCore.QRect(360, 320, 251, 191))
        self.photo4.setStyleSheet("border: 2px solid black; color: black;border-image: url(resim5.jpg);")
        self.photo4.setText("")
        self.photo4.setObjectName("photo4")
        self.nameLabel1_4 = QtWidgets.QLabel(Dialog)
        self.nameLabel1_4.setGeometry(QtCore.QRect(360, 520, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel1_4.setFont(font)
        self.nameLabel1_4.setObjectName("nameLabel1_4")
        self.photo3 = QtWidgets.QLabel(Dialog)
        self.photo3.setGeometry(QtCore.QRect(40, 320, 261, 191))
        self.photo3.setStyleSheet("border: 2px solid black; color: black;border-image: url(resim1.jfif);")
        self.photo3.setText("")
        self.photo3.setObjectName("photo3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelTitle.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Salon Pictures</p></body></html>"))
        self.closebutton.setText(_translate("Dialog", "Close"))
        self.detailButton1.setText(_translate("Dialog", "Detail"))
        self.nameLabel1.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:8pt;\">Skateboard</span></p></body></html>"))
        self.detailButton1_2.setText(_translate("Dialog", "Detail"))
        self.nameLabel1_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:8pt;\">Walking</span></p></body></html>"))
        self.detailButton1_4.setText(_translate("Dialog", "Detail"))
        self.detailButton1_3.setText(_translate("Dialog", "Detail"))
        self.nameLabel1_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:8pt;\">Swimming</span></p></body></html>"))
        self.nameLabel1_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:8pt;\">Fitness</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

